### ISSUE TITLE
Widget: Select multiple roles

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/wp-team-list#25]
This is a follow-up on #19.

Perhaps we can use something like [Select2](https://select2.github.io/) or another more lightweight library.

**Comment by swissspidy** [comment]
https://github.com/woocommerce/selectWoo is like Select2 but accessible.

**Comment by ocean90** [comment]
With the upcoming phases of Gutenberg it's not worth to continue improving the widget. The new block will support multiple roles.
